/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfacesGraficas;

import javax.swing.JOptionPane;



/**
 *
 * @author Emilsson Soler
 */




public class ModificarProducto extends javax.swing.JInternalFrame {

    
   
    public ModificarProducto() {
        initComponents();
         Principal.actualizarComboBoxProducto(productoCom);
         Principal.actualizarComboBoxProveedor(proveedorCombobox);
        llenarCampos();
        
    }
    
    public  void llenarCampos(){
    despensa.Producto prodcu = (despensa.Producto) productoCom.getSelectedItem();
    this.nombreField.setText(prodcu.getNombre());
    this.codigoField.setText(String.valueOf(prodcu.getCodigo()));
    this.precioCompraField.setText(String.valueOf(prodcu.getPrecioCompra()));
    this.precioVentaField.setText(String.valueOf(prodcu.getPrecioVenta()));
        if (prodcu.getRefrigeracion().isRefrigeracion()) {
            this.refrigeracionCheck.setSelected(true);
        }
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nombreField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        codigoField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        precioVentaField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        precioCompraField = new javax.swing.JTextField();
        proveedorCombobox = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        refrigeracionCheck = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        agregar = new javax.swing.JButton();
        productoCom = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();

        setClosable(true);

        nombreField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreFieldActionPerformed(evt);
            }
        });

        jLabel1.setText("Nombre");

        jLabel2.setText("Precio venta");

        jLabel3.setText("Codigo");

        jLabel4.setText("Precio compra");

        precioCompraField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                precioCompraFieldActionPerformed(evt);
            }
        });

        proveedorCombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel5.setText("Proveedor");

        refrigeracionCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refrigeracionCheckActionPerformed(evt);
            }
        });

        jLabel6.setText("Refrigeracion");

        agregar.setText("Modificar");
        agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarActionPerformed(evt);
            }
        });

        productoCom.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        productoCom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productoComActionPerformed(evt);
            }
        });

        jLabel7.setText("Elige producto");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel7)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel1)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5)))
                        .addGap(77, 77, 77)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nombreField)
                            .addComponent(codigoField)
                            .addComponent(precioVentaField)
                            .addComponent(precioCompraField)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(proveedorCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(productoCom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 22, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel6)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(21, 21, 21))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(refrigeracionCheck)
                    .addComponent(agregar))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(productoCom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(codigoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(precioVentaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(precioCompraField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(proveedorCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(refrigeracionCheck)
                    .addComponent(jLabel6))
                .addGap(9, 9, 9)
                .addComponent(agregar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nombreFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreFieldActionPerformed

    private void precioCompraFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_precioCompraFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_precioCompraFieldActionPerformed

    private void refrigeracionCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refrigeracionCheckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_refrigeracionCheckActionPerformed

    private void agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarActionPerformed
        try {
            if (nombreField.getText().isEmpty() || codigoField.getText().isEmpty() || precioVentaField.getText().isEmpty() || precioCompraField.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Campos vacios");
        }else{
        despensa.Producto prodcu = (despensa.Producto) productoCom.getSelectedItem();
        despensa.Proveedor prov = (despensa.Proveedor) proveedorCombobox.getSelectedItem();
        String nombre = nombreField.getText();
        int cod = Integer.parseInt(codigoField.getText());
        float precV= Float.parseFloat(precioVentaField.getText());
        float precC= Float.parseFloat(precioCompraField.getText());
        boolean refri = false;
            if (this.refrigeracionCheck.isSelected()) {
                refri = true;
                
            }
        despensa.DB.GestionProducto.modificarProductosTodosLosCamposUpdate(prov.getCodigo(), cod, nombre, precC, precV, refri, prodcu.getCodigoDB());
        Principal.actualizarInformacionTablaProducto(GestionProducto.tablaProductos);
        
        }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_agregarActionPerformed

    private void productoComActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productoComActionPerformed
        llenarCampos();
    }//GEN-LAST:event_productoComActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregar;
    private javax.swing.JTextField codigoField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField nombreField;
    private javax.swing.JTextField precioCompraField;
    private javax.swing.JTextField precioVentaField;
    private javax.swing.JComboBox<String> productoCom;
    private javax.swing.JComboBox<String> proveedorCombobox;
    private javax.swing.JCheckBox refrigeracionCheck;
    // End of variables declaration//GEN-END:variables
}
